### ISSUE TITLE
Unmarshalling file with & symbol in the name.

### ISSUE THREAD

**Issue by dfoulkes** [stoicflame/ofx4j#4]
**WHEN** 

`ResponseEnvelope envelope = unmarshaller.unmarshal(file);`

Parsing ofx file with the following statement transaction:

	        	<STMTTRN>
                    		<TRNTYPE>DEBIT
                    		</TRNTYPE>
                    		<DTPOSTED>20161110000044</DTPOSTED>
                    		<DTUSER></DTUSER>
                    		<TRNAMT>-01.01</TRNAMT>
                    		<FITID>17</FITID>
                    		<NAME>EE & T-MOBILE            </NAME>
                    		<MEMO></MEMO>
                    	</STMTTRN>

**THEN**

```
Caused by: java.io.IOException: Unexpected EOF
	at net.n3.nanoxml.StdXMLReader.read(Unknown Source)
	at net.n3.nanoxml.XMLUtil.read(Unknown Source)
	at net.n3.nanoxml.ContentReader.read(Unknown Source)
	at net.n3.nanoxml.ContentReaderBackdoor.read(ContentReaderBackdoor.java:24)
	at java.io.Reader.read(Reader.java:140)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.readCharacters(NanoXMLOFXReader.java:186)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:159)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.processOFXTag(NanoXMLOFXReader.java:136)
	at com.webcohesion.ofx4j.io.nanoxml.NanoXMLOFXReader.parseV1FromFirstElement(NanoXMLOFXReader.java:45)
	at com.webcohesion.ofx4j.io.BaseOFXReader.parse(BaseOFXReader.java:113)
	at com.webcohesion.ofx4j.io.BaseOFXReader.parse(BaseOFXReader.java:68)
	at com.webcohesion.ofx4j.io.AggregateUnmarshaller.unmarshal(AggregateUnmarshaller.java:44)
```

**Comment by stoicflame** [comment]
Thanks for the report.

Seems like the next step is to provide a unit test that reproduces the problem so we can validate a fix.

**Comment by ProjectFrank** [comment]
This exception is being thrown from the XMLReader itself. It throws this because `&` is used for escape sequences in XML, so the XML parser is expecting the `&` to be a part of an escape sequence.

`&` is itself a character that should be escaped in XML.

Source: https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

**Comment by Luiz-Otavio-Dorigon** [comment]
What is the forecast for this correction?

**Comment by stoicflame** [comment]
I actually can't tell if there's a bug? Shouldn't `<NAME>EE & T-MOBILE</NAME>` be invalid OFX? Shouldn't it be required to escape it to `<NAME>EE &amp; T-MOBILE</NAME>`

**Comment by edpichler** [comment]
It is not a bug. Here is the OFX specification:

<img width="797" height="715" alt="Image" src="https://github.com/user-attachments/assets/d01b1517-70e9-4a11-80b9-74a4c9232436" />

From https://financialdataexchange.org/wp-content/uploads/2025/12/OFX-Banking-Specification-v2.3.pdf

**Comment by stoicflame** [comment]
I'm really sorry, I'm still not clear what's being asserted as a bug. I thought the original bug was that the default parser won't parse a single unescaped `&` character. I acknowledge that parser failure, but it's not totally clear to me that it's a bug. The latest snippet of the spec posted by @edpichler seems to confirm that, no?

> ### 2.3.1.1 Special Characters
> 
> Special characters in OFX 2.2 are handled according to the XML standard. Characters such as ’<’, ’>’,
> ’&’, ’’’, and ’"’ are predefined in XML. Other character strings with many special characters should be
> enclosed in a CDATA section.

So the `&` needs to be escaped, yes? At least for OFX v2?

If we're working with a financial institution that needs its data parsed as OFX v1, then I acknowledge there's a case to be made that a single unescaped `&` character should be supported because OFX v1 wasn't based on strict XML. In this case, I think we'll need to use the more experimental and lenient `TagSoupOFXReader` instead of the `NanoXMLOFXReader` which requires XML compliance.
