### ISSUE TITLE
OFXServerException when connecting to Citi Credit Card

### ISSUE THREAD

**Issue by taihuapp** [stoicflame/ofx4j#61]
Has anyone successfully connected to Citi Credit Card?  I received a OFXServerException running ofx4j 1.28:

com.webcohesion.ofx4j.client.net.OFXServerException: Error with client request: Forbidden
	at com.webcohesion.ofx4j.client.net.OFXV1Connection.sendBuffer(OFXV1Connection.java:106)
	at com.webcohesion.ofx4j.client.net.OFXV1Connection.sendRequest(OFXV1Connection.java:59)
	at com.webcohesion.ofx4j.client.impl.FinancialInstitutionImpl.sendRequest(FinancialInstitutionImpl.java:151)
	at com.webcohesion.ofx4j.client.impl.FinancialInstitutionImpl.readAccountProfiles(FinancialInstitutionImpl.java:92)

**Comment by taihuapp** [comment]
It looks like the url for Citi Credit Card at [OFX Home](https://www.ofxhome.com/index.php/institution/view/629) is out dated.  No more 'Forbidden' response after I switch the old url to the one I found at [Gnucash Wiki](https://wiki.gnucash.org/wiki/OFX_Direct_Connect_Bank_Settings#Citi_Credit_Card).

**Comment by taihuapp** [comment]
Citi CreditCard also requires a non-null ClientUID.
